// A list of all actions in the system.
import { createTypes } from 'reduxsauce'

export default createTypes(`
  STEP_DATA_UPDATE

  LOGIN_SUCCESS
  LOGIN_OUT

  FORCE_LOGIN
  OPEN_LOGIN
  OPEN_SIGNUP

  GETUSER_SUCCESS
  PUTUSER_SUCCESS
  GETUSERSTATVIEW_SUCCESS

  GET_GROUPTOUR_AUTHOR
  DEL_GROUPTOUR_AUTHOR

  LOGIN_SIGNUP_CB


  SET_BOOK_DATA
  SET_CURRENCY
  SET_CURRENCYTRIP
  SET_LOCALE
  SET_FILTER_DATA
  SET_RESULT_DATA
`)
